name:                haskell-in-a-week
version:             0.1.0.0
github:              "andreamanfroi/haskell-in-a-week"
license:             BSD3
author:              "Andrea Manfroi"
maintainer:          "andreamanfroi@libero.it"
copyright:           "2023 Andrea Manfroi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andreamanfroi/haskell-in-a-week#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- random
- mtl
- QuickCheck

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: 
    - src
    - src/collatz
    - src/pangram
    - src/text
    - src/atbash
    - src/perfect_number
    - src/gcd
    - src/quickcheck
    - src/isogram
executables:
  haskell-in-a-week-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-in-a-week

tests:
  haskell-in-a-week-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-in-a-week
    - hspec
    - hspec-discover
    - QuickCheck
